name: event_app_anacity
description: An app for events.
publish_to: "none"
version: 1.0.2+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.4.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  email_validator: ^2.1.17
  cached_network_image: ^3.3.1
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

